'use strict';
const express = require('express');
const router = express.Router();
const deliveryOrderController = require('../controllers/deliveryOrderController');
const authMiddleware = require('../middleware/authMiddleware');
router.get('/assigned', authMiddleware, deliveryOrderController.getAssignedOrders);
router.put('/:orderId/status', authMiddleware, deliveryOrderController.updateOrderStatus);
router.put('/:orderId/payment', authMiddleware, deliveryOrderController.updateOrderPayment);
router.post('/:orderId/generate-payment-link', authMiddleware, deliveryOrderController.generatePaymentLink);
router.get('/:orderId/check-payment-status', authMiddleware, deliveryOrderController.checkPaymentStatus);
module.exports = router;
